### ISSUE TITLE
python module request is not installed by default on Mac

### ISSUE THREAD

**Issue by jpc0** [shakeyourbunny/RWMS#18]
python module request is not installed by default on Mac

As was mentioned [https://ludeon.com/forums/index.php?topic=48518.msg457879#msg457879](here)

Maybe include a section in the readme that this module needs to be installed as well for mac users

a simple `pip3 install request` solves the problem

**Comment by shakeyourbunny** [comment]
Hi,

added support for requirements.txt and a script to install all missing (and needed) Python modules to the current GIT revision https://github.com/shakeyourbunny/RWMS/commit/e9d55fae2ecc4c9158f091fc7f518c747cfd1b18.

I also included some installation documentation for OSX.
