### ISSUE TITLE
Unknown mods

### ISSUE THREAD

**Issue by AngryScandinavian** [shakeyourbunny/RWMS#2]
[rwms_unknown_mods_20190413-1457.json.txt](https://github.com/shakeyourbunny/RWMS/files/3076777/rwms_unknown_mods_20190413-1457.json.txt)

**Comment by shakeyourbunny** [comment]
please use the issue tracker for RWMSDB für unknown mods: https://github.com/shakeyourbunny/RWMSDB/issues

moved the ticket to https://github.com/shakeyourbunny/RWMSDB/issues/6
