### ISSUE TITLE
Unable to use executable. ModuleNotFoundError

### ISSUE THREAD

**Issue by Wolfehart** [shakeyourbunny/RWMS#29]
I'm getting this error when launching the exe of the latest release (0.98.4). I have used v0.94.2 couple of months ago and decided to update the executable.

Traceback (most recent call last):
  File "rwms_sort.py", line 17, in <module>
ModuleNotFoundError: No module named 'bs4'
[10800] Failed to execute script rwms_sort

![cmd_2019-07-30_11-27-19](https://user-images.githubusercontent.com/14332574/62098468-01300c80-b2bd-11e9-8e31-485df33c9414.png)

**Comment by SpookieWookie** [comment]
Getting the same issue here, identical error
Last version that works fine for me is 0.94.7
![image](https://user-images.githubusercontent.com/29523103/62158530-8cce8b00-b307-11e9-86b4-250cf57812e1.png)

**Comment by SpookieWookie** [comment]
![image](https://user-images.githubusercontent.com/29523103/62158513-83ddb980-b307-11e9-93aa-721515a789f9.png)

**Comment by capitanjal** [comment]
bs4 is BeautifulSoup4 is a dependence of python you get that error because you haven't installed it

edit: i installed bs4 and didn't work either

**Comment by SpookieWookie** [comment]
Yeah I'd already tried that

**Comment by TwistedMinds2** [comment]
Latest version seems to be 0.98.9, but for some reason the executable file for windows is called 0.94.9 (30-07-2019). I cannot make it work either even after I reinstalled python 3.7.4 and 3.6, with relevant modules. (0.98.9 -> 0.94.9)

The source code is named correctly and the .py included is working.

Quick edit: Same for the previous version (0.98.4 -> 0.94.8, executable only)

**Comment by wackoamd1** [comment]
yeah got the same problem

**Comment by felixkempf** [comment]
Windows 10 64bit here. Last functioning version for me is `rwms_sort-0.94.6` .

Everything newer just closes the command window instantly and does nothing.


@TwistedMinds2 I think this is just some kind of unintentional number switching in the titles for the releases

**Comment by Wolfehart** [comment]
I should add that i'm using win7 home premium 64 bits when launching the application. If you need any more info, I will gladly provide them to fix this case.

My last working version is the same with spookie, which is 0.94.7. Seems to be working okay so far.

**Comment by capitanjal** [comment]
@shakeyourbunny  there is a incompatibility in the program with people that don't have installed the SDK check it out

**Comment by normous** [comment]
> 
> 
> @shakeyourbunny there is a incompatibility in the program with people that don't have installed the SDK check it out

I'm having the same issue.  Which SDK are you referring to?

**Comment by ghost** [comment]
It's just a problem with executable. Running bat directly from source works fine.

**Comment by SpookieWookie** [comment]
I built it from source after installing BS4 - and it was fine for me. I don't know GitHub too well but if I can attach it here or something I can at least provide a hopefully working executable :)

**Comment by wackoamd1** [comment]
> I built it from source after installing BS4 - and it was fine for me. I don't know GitHub too well but if I can attach it here or something I can at least provide a hopefully working executable :)

u should just be able to drag and drop a file in the reply

**Comment by shakeyourbunny** [comment]
If you want to have a windows executable, please visit the releases page.

I reversed my decision not to provide windows executables, main reason was that I temporarily moved to Linux and had no longer access to a Windows machine.

https://github.com/shakeyourbunny/RWMS/releases/

If you wish to run the source release you will have to do the following:
- install Python for Windows ( https://www.python.org/downloads/windows/ take one of the executable installers, x86-64 if 64 Bit Windows )
- let Python add itself in the system path (if not successfull: hit Windows+Pause -> Advanced System Settings -> Advanced -> Environment Variables -> add the path to python to the Path variable)
- run the "install_requirements.cmd" (Linux / OSX: "install_requirements.sh") to install all missing dependencies.

Have fun!

PS: the most recent version of RWMS is indeed 0.94.9, I had some confusion on my part for the numbering, this was fixed some minutes ago.
