### ISSUE TITLE
Cannot start script

### ISSUE THREAD

**Issue by brothan323** [shakeyourbunny/RWMS#32]
No idea why but the CMD box keeps closing due to a cannot start script error.

Edit: Versions above 94.7 don't work

**Comment by ThatRand0meR** [comment]
My error:

Loading and parsing ModsConfig.xml
Loading mod data.
Traceback (most recent call last):
  File "rwms_sort.py", line 286, in <module>
    if mod_entry[1] is not None:
IndexError: list index out of range

**Comment by shakeyourbunny** [comment]
Does the bug still occur with 0.95.0a? 

https://github.com/shakeyourbunny/RWMS/releases/tag/0.95.0a

**Comment by SeppDE** [comment]
Seems so. I just downloaded the 0.95.0a release, edited the config files with the paths and the .exe is simply closing after starting. Nothing to see directly. after recording the startup i found the error i got.

![grafik](https://user-images.githubusercontent.com/7773216/63210251-3c6b7180-c0ec-11e9-9b16-8c28e5765d2e.png)

**Comment by shakeyourbunny** [comment]
Oh my gush... I think I know why this problem is occuring... in my main Python environment there is no bs4 module, just in the virtual env. At the time building the the executable, the module will not be included then... 

I will fix it ASAP. On some other site, somebody has a similiar problem.

**Comment by shakeyourbunny** [comment]
https://github.com/shakeyourbunny/RWMS/releases/tag/0.95.1 should do the trick now.

please confirm, at least on my system the executable does its thing correctly.

**Comment by SeppDE** [comment]
Tested and it worked (at least on my side)

**Comment by shakeyourbunny** [comment]
I also had some other sources which could confirm that, so happy evening for now ;D
