### ISSUE TITLE
Dry run option

### ISSUE THREAD

**Issue by edjacob25** [shakeyourbunny/RWMS#35]
So, a common option in this kind of tools is a "dry run", in which you can see which changes are going to be applied but not actually doing any of them. I think  is quite an useful feature and an easy task, so I went ahead a did it in my fork. 

I was wondering if you are interested in a pull request for it.

**Comment by EnderShadow** [comment]
Shouldn't this issue be closed?

**Comment by edjacob25** [comment]
Yeah, I'll do it.
