### ISSUE TITLE
Missing mods

### ISSUE THREAD

**Issue by Deathawaits4** [shakeyourbunny/RWMS#4]
{
 "Call of Cthulhu - Cosmic Horrors": "not_categorized",
 "[Ling]Limit Raid1.0": "not_categorized",
 "time": "Fri Apr 19 00:59:13 2019"
}

**Comment by johnrando** [comment]
more:

{
 "Better Roads": "not_categorized",
 "CCP's Mental Break Tweaks": "not_categorized",
 "CCP's Stone Tweaks Vanilla": "not_categorized",
 "Cheaper Carpet": "not_categorized",
 "Colorful Traits": "not_categorized",
 "Everyone is Queer": "not_categorized",
 "Give Me A Moment": "not_categorized",
 "Herd Migration Revival": "not_categorized",
 "Hold Open Opens Doors": "not_categorized",
 "I Can Fix It!": "not_categorized",
 "Less Default Hair": "not_categorized",
 "Less Stupid Romance Attempt": "not_categorized",
 "LesserToxicFallout": "not_categorized",
 "Masturbation": "not_categorized",
 "Realistic Smokeleaf": "not_categorized",
 "Shrink Corpse Buff 1.0": "not_categorized",
 "Stronger Penoxycyline (1.0)": "not_categorized",
 "Stronger Penoxycyline - Preporix Edition (1.0)": "not_categorized",
 "There's not enough time!": "not_categorized",
 "Where is rich soil? (Revived)": "not_categorized",
 "[1.0] Movable Hydroponics": "not_categorized",
 "[1.0] Movable Pumps": "not_categorized",
 "[1.0]Gourmand trait nerf": "not_categorized",
 "[KIR]No Turret Barrels Replacing[1.0]": "not_categorized",
 "[T] ExpandedCrops": "not_categorized",
 "[T] MoreFloors \u4e2d\u6587\u7ffb\u8bd1": "not_categorized",
 "[sd] conduit wall": "not_categorized",
 "time": "Thu Apr 18 20:14:14 2019"
}

**Comment by Deathawaits4** [comment]
"BetterLoading": "not_categorized",
 "Call of Cthulhu - Cosmic Horrors": "not_categorized",
 "Raiderpedes": "not_categorized",
 "Replimat": "not_categorized",
 "RimGate - Jaffa, Kree! 6.0.0": "not_categorized",
 "[Ling]Limit Raid1.0": "not_categorized",

another batch of mods, note that betterLoading should even be on top of core.

**Comment by Thirsk** [comment]
{
 "Big Batteries": "not_categorized",
 "Community Core Library - Vanilla Tweaks": "not_categorized",
 "[JPT] Soft Warm Beds": "not_categorized",
 "time": "Wed Apr 24 17:47:16 2019"
}
Commenting here because I didn't see the sense in opening a new issue just for these.

**Comment by shakeyourbunny** [comment]
One issue per update please.
